//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondWorldWebApi.GIANewService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.reportcheck.model.ngs.com/", ConfigurationName="GIANewService.ReportCheckWS")]
    public interface ReportCheckWS {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiamondWorldWebApi.GIANewService.processRequestResponse processRequest(DiamondWorldWebApi.GIANewService.processRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.processRequestResponse> processRequestAsync(DiamondWorldWebApi.GIANewService.processRequestRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponse getReportCheckDateResult(DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponse> getReportCheckDateResultAsync(DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiamondWorldWebApi.GIANewService.downloadPDFReportResponse downloadPDFReport(DiamondWorldWebApi.GIANewService.downloadPDFReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.downloadPDFReportResponse> downloadPDFReportAsync(DiamondWorldWebApi.GIANewService.downloadPDFReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processRequest", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public DiamondWorldWebApi.GIANewService.processRequestRequestBody Body;
        
        public processRequestRequest() {
        }
        
        public processRequestRequest(DiamondWorldWebApi.GIANewService.processRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class processRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public processRequestRequestBody() {
        }
        
        public processRequestRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processRequestResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public DiamondWorldWebApi.GIANewService.processRequestResponseBody Body;
        
        public processRequestResponse() {
        }
        
        public processRequestResponse(DiamondWorldWebApi.GIANewService.processRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class processRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public processRequestResponseBody() {
        }
        
        public processRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportCheckDateResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportCheckDateResult", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequestBody Body;
        
        public getReportCheckDateResultRequest() {
        }
        
        public getReportCheckDateResultRequest(DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getReportCheckDateResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getReportCheckDateResultRequestBody() {
        }
        
        public getReportCheckDateResultRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportCheckDateResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportCheckDateResultResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponseBody Body;
        
        public getReportCheckDateResultResponse() {
        }
        
        public getReportCheckDateResultResponse(DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getReportCheckDateResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getReportCheckDateResultResponseBody() {
        }
        
        public getReportCheckDateResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFReport", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public DiamondWorldWebApi.GIANewService.downloadPDFReportRequestBody Body;
        
        public downloadPDFReportRequest() {
        }
        
        public downloadPDFReportRequest(DiamondWorldWebApi.GIANewService.downloadPDFReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadPDFReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public downloadPDFReportRequestBody() {
        }
        
        public downloadPDFReportRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFReportResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public DiamondWorldWebApi.GIANewService.downloadPDFReportResponseBody Body;
        
        public downloadPDFReportResponse() {
        }
        
        public downloadPDFReportResponse(DiamondWorldWebApi.GIANewService.downloadPDFReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadPDFReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] @return;
        
        public downloadPDFReportResponseBody() {
        }
        
        public downloadPDFReportResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportCheckWSChannel : DiamondWorldWebApi.GIANewService.ReportCheckWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportCheckWSClient : System.ServiceModel.ClientBase<DiamondWorldWebApi.GIANewService.ReportCheckWS>, DiamondWorldWebApi.GIANewService.ReportCheckWS {
        
        public ReportCheckWSClient() {
        }
        
        public ReportCheckWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportCheckWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportCheckWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportCheckWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiamondWorldWebApi.GIANewService.processRequestResponse DiamondWorldWebApi.GIANewService.ReportCheckWS.processRequest(DiamondWorldWebApi.GIANewService.processRequestRequest request) {
            return base.Channel.processRequest(request);
        }
        
        public string processRequest(string arg0) {
            DiamondWorldWebApi.GIANewService.processRequestRequest inValue = new DiamondWorldWebApi.GIANewService.processRequestRequest();
            inValue.Body = new DiamondWorldWebApi.GIANewService.processRequestRequestBody();
            inValue.Body.arg0 = arg0;
            DiamondWorldWebApi.GIANewService.processRequestResponse retVal = ((DiamondWorldWebApi.GIANewService.ReportCheckWS)(this)).processRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.processRequestResponse> DiamondWorldWebApi.GIANewService.ReportCheckWS.processRequestAsync(DiamondWorldWebApi.GIANewService.processRequestRequest request) {
            return base.Channel.processRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.processRequestResponse> processRequestAsync(string arg0) {
            DiamondWorldWebApi.GIANewService.processRequestRequest inValue = new DiamondWorldWebApi.GIANewService.processRequestRequest();
            inValue.Body = new DiamondWorldWebApi.GIANewService.processRequestRequestBody();
            inValue.Body.arg0 = arg0;
            return ((DiamondWorldWebApi.GIANewService.ReportCheckWS)(this)).processRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponse DiamondWorldWebApi.GIANewService.ReportCheckWS.getReportCheckDateResult(DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest request) {
            return base.Channel.getReportCheckDateResult(request);
        }
        
        public string getReportCheckDateResult(string arg0) {
            DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest inValue = new DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest();
            inValue.Body = new DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequestBody();
            inValue.Body.arg0 = arg0;
            DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponse retVal = ((DiamondWorldWebApi.GIANewService.ReportCheckWS)(this)).getReportCheckDateResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponse> DiamondWorldWebApi.GIANewService.ReportCheckWS.getReportCheckDateResultAsync(DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest request) {
            return base.Channel.getReportCheckDateResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.getReportCheckDateResultResponse> getReportCheckDateResultAsync(string arg0) {
            DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest inValue = new DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequest();
            inValue.Body = new DiamondWorldWebApi.GIANewService.getReportCheckDateResultRequestBody();
            inValue.Body.arg0 = arg0;
            return ((DiamondWorldWebApi.GIANewService.ReportCheckWS)(this)).getReportCheckDateResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiamondWorldWebApi.GIANewService.downloadPDFReportResponse DiamondWorldWebApi.GIANewService.ReportCheckWS.downloadPDFReport(DiamondWorldWebApi.GIANewService.downloadPDFReportRequest request) {
            return base.Channel.downloadPDFReport(request);
        }
        
        public byte[] downloadPDFReport(string arg0) {
            DiamondWorldWebApi.GIANewService.downloadPDFReportRequest inValue = new DiamondWorldWebApi.GIANewService.downloadPDFReportRequest();
            inValue.Body = new DiamondWorldWebApi.GIANewService.downloadPDFReportRequestBody();
            inValue.Body.arg0 = arg0;
            DiamondWorldWebApi.GIANewService.downloadPDFReportResponse retVal = ((DiamondWorldWebApi.GIANewService.ReportCheckWS)(this)).downloadPDFReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.downloadPDFReportResponse> DiamondWorldWebApi.GIANewService.ReportCheckWS.downloadPDFReportAsync(DiamondWorldWebApi.GIANewService.downloadPDFReportRequest request) {
            return base.Channel.downloadPDFReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<DiamondWorldWebApi.GIANewService.downloadPDFReportResponse> downloadPDFReportAsync(string arg0) {
            DiamondWorldWebApi.GIANewService.downloadPDFReportRequest inValue = new DiamondWorldWebApi.GIANewService.downloadPDFReportRequest();
            inValue.Body = new DiamondWorldWebApi.GIANewService.downloadPDFReportRequestBody();
            inValue.Body.arg0 = arg0;
            return ((DiamondWorldWebApi.GIANewService.ReportCheckWS)(this)).downloadPDFReportAsync(inValue);
        }
    }
}
